let credits = parseInt(localStorage.getItem('credits')||'0',10);document.getElementById('credits').innerText=credits;
const answers=["Yes","No","Ask again later","Definitely","Very doubtful","Without a doubt","My sources say no","Signs point to yes"];
let history=JSON.parse(localStorage.getItem('history')||'[]');updateHistoryDisplay();
function randomAnswer(){return answers[Math.floor(Math.random()*answers.length)];}
function showAnswer(ans){document.getElementById('answer').innerText=ans;}
function updateHistoryDisplay(){const list=document.getElementById('historyList');list.innerHTML='';history.slice().reverse().forEach(item=>{const li=document.createElement('li');li.textContent=`Q: ${item.question} → A: ${item.answer}`;list.appendChild(li);});}
function createEtherealParticles(){const container=document.getElementById('ball-container');for(let i=0;i<12;i++){const particle=document.createElement('div');particle.classList.add('particle');particle.style.left=`${Math.random()*80+10}px`;particle.style.top=`${Math.random()*80+10}px`;const size=Math.random()*8+4;particle.style.width=particle.style.height=`${size}px`;const hue=180+Math.random()*60;particle.style.background=`radial-gradient(circle, hsla(${hue},100%,90%,0.8) 0%, hsla(${hue},100%,90%,0.05) 80%)`;particle.style.animationDuration=`${2+Math.random()}s`;container.appendChild(particle);setTimeout(()=>particle.remove(),2500);}}
function askQuestion(){const question=document.getElementById('questionInput').value.trim();if(!question){alert("Please type a question before asking the Magic 8 Ball!");return;}
if(credits>0){credits--;localStorage.setItem('credits',credits);document.getElementById('credits').innerText=credits;const ball=document.getElementById('ball');ball.classList.add('shake');const sound=document.getElementById('shakeSound');sound.currentTime=0;sound.play();
setTimeout(()=>{ball.classList.remove('shake');createEtherealParticles();const answer=randomAnswer();showAnswer(answer);ball.classList.add('pulse');setTimeout(()=>ball.classList.remove('pulse'),3000);history.push({question,answer});if(history.length>5)history.shift();localStorage.setItem('history',JSON.stringify(history));updateHistoryDisplay();},600);}else{alert("You have no credits! Buy a pack to continue.");}}
async function buyPack(pack){const res=await fetch('/.netlify/functions/create-checkout-session',{method:'POST',body:JSON.stringify({pack})});const data=await res.json();window.location.href=data.url;}
document.getElementById('clearHistoryBtn').addEventListener('click',()=>{if(confirm("Are you sure you want to clear your question history?")){history=[];localStorage.removeItem('history');updateHistoryDisplay();}});
